FROM node:20-alpine AS builder
WORKDIR /app

ARG DJANGO_BACKEND
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET

ENV DJANGO_BACKEND=$DJANGO_BACKEND
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app

ARG DJANGO_BACKEND
ARG NEXTAUTH_URL
ARG NEXTAUTH_SECRET

ENV NODE_ENV=production
ENV DJANGO_BACKEND=$DJANGO_BACKEND
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

ENV HOSTNAME="0.0.0.0"
ENV PORT=3000

CMD ["node", "server.js"]