import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import "./lib/fontawesome";
import Navbar from "./components/layout/Navbar";
import Footer from "./components/layout/Footer";
import StoreProvider from "./providers/StoreProvider";
import AuthProvider from '@/app/providers/AuthProvider';
import Analytics from "./components/layout/Analytics";
import AdSense from "./components/layout/AdSense";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <AdSense />
      </head>
      <body
        className={`${inter.variable} ${openSans.variable} antialiased`}
      >
        <StoreProvider>
          <AuthProvider>
            <Navbar />
            <main className="pt-14 pb-32">
              {children}
            </main>
            <Footer />
          </AuthProvider>
        </StoreProvider>
      </body>
      <Analytics />
    </html>
  );
}
